### ISSUE TITLE
[UI3] Deletion Requests Page has poor layout

### ISSUE THREAD

**Issue by devramsean0** [hackclub/hcb#12101]
### Describe your goals

I'm trying to process the deletion request queue whilst opted into UI3

### Describe the bug

I'm trying to process a deletion request, but the comment padding is weird being crushed into the top corner, and it seems like the close req button was accidentally moved outside of the information container.

It also feels weird being centered to the left instead of the center but maybe that's just the new design style. Not sure

<img width="1922" height="923" alt="Image" src="https://github.com/user-attachments/assets/a6bdcb04-5885-4e4f-84ee-b5c7f8b81b9f" /> (Hopefully everything Pii hidden)

**Comment by manu-gurudath** [comment]
fixed!

**Comment by Luke-Oldenburg** [comment]
@manuthecoder I'm still encountering this in production. Can you provide a screenshot of what it looks like for you?
