### ISSUE TITLE
[UI3] Weird spacing in documents heading and poor page title

### ISSUE THREAD

**Issue by Luke-Oldenburg** [hackclub/hcb#12128]
Admin tool top heading is off and spacing of elements at the top of the page seems to be weird in general. I think it would be best to center the "Documents" text with the admin tool and reduce the distance between the divider and the two tabs below it. Also, the admin tool disappears when going to the "Financial statements" tab which affects the location of the content below it.
<img width="1666" height="339" alt="Image" src="https://github.com/user-attachments/assets/4a0ccfb0-9c1a-4471-af4b-080db45b2e28" />

The title of the documents page is much longer than the statements page.
<img width="411" height="166" alt="Image" src="https://github.com/user-attachments/assets/0e1d1a1b-6442-48a5-9589-47c8620c1d7a" />

<img width="332" height="54" alt="Image" src="https://github.com/user-attachments/assets/63834789-ae71-4407-a9ab-8d6818b8a7e3" />

**Comment by manu-gurudath** [comment]
fixed!

**Comment by Luke-Oldenburg** [comment]
It's better but I think it could still use to be improved. Most of the issues are still there just reduced how noticeable they are.

**Comment by manu-gurudath** [comment]
<img width="1544" height="923" alt="Image" src="https://github.com/user-attachments/assets/a7570b3f-1adf-4203-a3fa-e7de54fc3325" />

fixed divider distance and title

**Comment by Luke-Oldenburg** [comment]
@manuthecoder can we get the padding on the admin tool fixed please?
